### ISSUE TITLE
Openstack not showing up under cloud providers

### ISSUE THREAD

**Issue by curzona** [yandex-qatools/teamcity-openstack-plugin#16]
I built and installed teamcity-openstack-plugin but Openstack does not show up under cloud providers.
Maybe there is a step I'm missing?

Here is what I did:

```
sudo apt-get install maven
sudo apt-get install openjdk-7-jdk

git clone https://github.com/yandex-qatools/teamcity-openstack-plugin.git

mvn install:install-file -Dfile=/opt/teamcity-server/webapps/ROOT/WEB-INF/lib/cloud-interface.jar -DgroupId=jetbrains.buildServer.clouds -DartifactId=cloud-interface -Dversion=9.0 -Dpackaging=jar
mvn install:install-file -Dfile=/opt/teamcity-server/webapps/ROOT/WEB-INF/lib/cloud-shared.jar -DgroupId=jetbrains.buildServer.clouds -DartifactId=cloud-shared -Dversion=9.0 -Dpackaging=jar
mvn install:install-file -Dfile=/opt/teamcity-server/webapps/ROOT/WEB-INF/lib/cloud-server.jar -DgroupId=jetbrains.buildServer.clouds -DartifactId=cloud-server -Dversion=9.0 -Dpackaging=jar
mvn install:install-file -Dfile=/opt/teamcity-server/webapps/ROOT/WEB-INF/lib/openapi.jar -DgroupId=jetbrains.buildServer.clouds -DartifactId=openapi -Dversion=9.0 -Dpackaging=jar

mvn -X clean package

sudo cp target/cloud-openstack.zip /var/teamcity-server/.BuildServer/plugins/

sudo service teamcity-server restart
```

I confirmed the plugin is installed by checking _Administrator > Plugin List_

```
cloud-openstack Cloud Openstack Integration for TeamCity
snapshot-20151206164146 Yandex LLC  <TeamCity Data Directory>/.unpacked/cloud-openstack
```

Openstack does not show up under _Administrator > Agent Cloud > New Profile > Cloud Type_

Maybe there is a step I'm missing?

**Comment by axel3rd** [comment]
Hello @curzona,

Is this problem still relevant? Have you the capacity to test with a coming soon 1.0-SNAPSHOT (builded by an OSS CI platform) on your (2017.x?) TeamCity ?

Best regards

**Comment by axel3rd** [comment]
@curzona : I let you test with last [1.0-SNAPSHOT](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildSnapshotIntegration/.lastSuccessful/cloud-openstack.zip?guest=1). Please reopen with log if not works.
