### ISSUE TITLE
Need to support Openstack v3 API

### ISSUE THREAD

**Issue by koldrid** [yandex-qatools/teamcity-openstack-plugin#18]
As of Mitaka the v2.0 apis no longer exist. This plugin will not work with Mitaka.

**Comment by jaxzin** [comment]
👍

**Comment by axel3rd** [comment]
I had a look on it, but not simple. Openstack plugin is using [jclouds](https://jclouds.apache.org/) library. 
It does not currently implements v3 authentication => [JCLOUDS-114](https://issues.apache.org/jira/browse/JCLOUDS-114) is a prerequisite.
After that, perhaps it is just [one character change](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/master/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackApi.java#L41) :stuck_out_tongue_winking_eye:

**Comment by axel3rd** [comment]
Keystone v3 really supported after fix for #26

**Comment by axel3rd** [comment]
[1.0-SNAPSHOT](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildSnapshotIntegration/1413217:id/cloud-openstack.zip) available for tests.
