### ISSUE TITLE
instance removing while profile changes

### ISSUE THREAD

**Issue by mavlyutov** [yandex-qatools/teamcity-openstack-plugin#2]
Если мы меняем клаудный профиль, то все существующие инстансы потеряются, мы их не увидим. Нужно при инициализации клаудного клиента найти все существующие инстансы и их добавить. Сейчас эта проблема решается тем, что все при вызове CloudClient.dispose() все инстансы останавливаются, хотя это совсем не обязательно.

**Comment by aefimov** [comment]
Хочу записать cloudImageId в агента, правильно ли я думаю?  Почему хочу — найти Server по uuid я смогу, найти из него image я тоже смогу, но если получится так, что к разным CloudImage подходит один и тот же Openstack Image, получится что мы неверно переназначим агентов. Можно еще конечно на имя агента смотреть и зону. Но в общем случае наверное надо в агента писать ID профиля.

**Comment by axel3rd** [comment]
_Oneself todo: Check behavior on 1.0-SNAPSHOT and frizzlywitch fix_

**Comment by axel3rd** [comment]
Not easy, all `dispose` mechanism should be reviewed. 
Perhaps a way with [Cloud support : API usage for "mark for termination" ?](https://teamcity-support.jetbrains.com/hc/en-us/community/posts/360003028480-Cloud-support-API-usage-for-mark-for-termination-)

**Comment by promiteyka** [comment]
This problem is still exist, no progress so far. Is there any news for fix it?
I asked a Jetbrains support from enterprise channel for help with https://teamcity-support.jetbrains.com/hc/en-us/community/posts/360003028480-Cloud-support-API-usage-for-mark-for-termination-

**Comment by axel3rd** [comment]
> This problem is still exist, no progress so far. Is there any news for fix it?

No news from my side. Not know how to currently fix it.

**Comment by paksv** [comment]
@axel3rd replied on forum. Would you like to continue the discussion here?

**Comment by axel3rd** [comment]
>@axel3rd replied on forum. Would you like to continue the discussion here or on forum?

Hi @paksv, here is better IMO. Many thanks for you analysis.

Perhaps just a complementary question: Is there some guideline for doing async jobs in a TeamCity plugin (*OpenstackCloudClient#isInitialized should return only after plugin got initial state from the openstack* & *periodically synchronize state of cloud instances*), or plugin should manage Threads itself (and stopped in `OpenstackCloudImage#dispose` )?

----

**For fix the problem, see: https://teamcity-support.jetbrains.com/hc/en-us/community/posts/360003028480/comments/360001677480**

**Comment by paksv** [comment]
Hi @axel3rd, the main recommendation (this is actually a requirement for us internally) for executors is that they should be daemon, so they don't prevent instance from stopping. 
There are two helpers available:
1) jetbrains.buildServer.util.executors.ExecutorsFactory - thread factory that does all necessary things
2) jetbrains.buildServer.serverSide.executors.ExecutorServices - a spring bean that gives you a way to schedule tasks without having to maintain your own executor. You can use jetbrains.buildServer.serverSide.executors.ExecutorServices#getNormalExecutorService for scheduled tasks

**Comment by axel3rd** [comment]
Many thanks @paksv 😗

**Comment by promiteyka** [comment]
Hello @axel3rd 
Is there any news for fix it? :)

**Comment by axel3rd** [comment]
> Hello @axel3rd
> Is there any news for fix it? :)

Not sure to have time to work on that in a short term. Any PR is welcome.

**Comment by promiteyka** [comment]
@axel3rd 
We can not wait long, we would like to close the problem in the next month. Maybe you are ready to modify it on a commercial basis?
Give me your mail, we will discuss personally if interested.

**Comment by axel3rd** [comment]
@promiteyka : Not interested sorry (no time currently, and any *commercial basis* is too complicated to instruct legally in my current "French-covid-shortwork" context).

This plugin is opensource, not really maintained by the original team which have produced it.
I have done some updates because we are using OpenStack & TeamCity in my company, but that's all.
If any other people would spend time to improve this plugin, it would be preferable ; to grow up the community on that project.

**Comment by paksv** [comment]
@promiteyka I can probably help a bit here, if you can provide an infrastructure to test on.

**Comment by axel3rd** [comment]
> if you can provide an infrastructure to test on

For information:
- See [Dev Contrib: UT with AWS](https://github.com/yandex-qatools/teamcity-openstack-plugin/wiki/Dev-Contrib:-UT-with-AWS) wiki to quick install a test OpenStack (pike) platform on AWS
- Any PR is ran (unit tests, ...) via [Pull request analysis](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityThirdPartyPlugins_OpenStackCloudSupport_PullRequestAnalysis) build (on an instance from AMI with my AWS account)
