### ISSUE TITLE
Can't run multiple agents if this plugin is active

### ISSUE THREAD

**Issue by Sushisource** [yandex-qatools/teamcity-openstack-plugin#20]
I was recently trying to run multiple agents inside docker images on an openstack host, but this plugin breaks this scenario due to finding the openstack UUID and then forcing the agent name. Only one agent can succeed since it grabs the name first, and the rest fail.

Being able to disable that check, and have it use the name specified in the agent's property file would fix that issue.

I have opened a separate issue on the TC tracker to allow disabling plugins on a per-agent basis, which would allow a workaround.

Thanks!

**Comment by axel3rd** [comment]
+1
