### ISSUE TITLE
ability to choose agent pool

### ISSUE THREAD

**Issue by promiteyka** [yandex-qatools/teamcity-openstack-plugin#47]
Now all agents assign automatically to the default agent pool.
Is it possible to add the ability to select an agent pool for a specific instance? as done in other teamcity plugins.

**Comment by axel3rd** [comment]
@promiteyka 

> Now all agents assign automatically to the default agent pool.

This behavior comes from a specific version of this plugin ? or after a TeamCity version upgrade ?

> Is it possible to add the ability to select an agent pool for a specific instance? as done in other teamcity plugins.

Did you have some screenshot of this use case on some other cloud plugin ? 
I'm not sure to understand the use case.

**Comment by promiteyka** [comment]
> @promiteyka
> 
> > Now all agents assign automatically to the default agent pool.
> 
> This behavior comes from a specific version of this plugin ? or after a TeamCity version upgrade ?
> 
This is the default behavior of this plugin, it always has been.
> > Is it possible to add the ability to select an agent pool for a specific instance? as done in other teamcity plugins.
> 
> Did you have some screenshot of this use case on some other cloud plugin ?
> I'm not sure to understand the use case.
Agent pools - https://www.jetbrains.com/help/teamcity/agent-pools.html
We have several agent pools, different projects use different agent pools for security and configuration reason. In the open stack plugin there is no way to put agents in a particular pool. On the screenshot shows this ability in vmware vsphere plugin for example, but this possibility is also in other cloud plugins.
![image](https://user-images.githubusercontent.com/60609305/79695727-2fa5ab80-8281-11ea-9543-b281f64c5640.png)

**Comment by promiteyka** [comment]
@axel3rd 
If the plugin had the ability to set the agent pool in the yaml for a specific instance it would be very cool

**Comment by axel3rd** [comment]
When you create/update a pool, you can *assign agents*:

![image](https://user-images.githubusercontent.com/2912441/79698683-c75bc780-828a-11ea-93a6-7f01533982fa.png)

Is it not a response for your use case if you select the cloud configuration ?

**Comment by promiteyka** [comment]
Every day we start about 300 agents with different operating systems and in different agent pools; it’s too difficult to move agents to agent pools manually from web interface or using external automation through api.
We want to migrate from vmware vsphere plugin to openstack. But this limitation does not yet allow us to move on.

**Comment by axel3rd** [comment]
@promiteyka : See my screenshot, when you *assign* agents in a pool, for cloud agents, only "image" can be selected (not instancied VM). I think in this case agents/VM instanciated are linked to the pool.

**Comment by promiteyka** [comment]
Yes, you are right. I tried to move the image to another pool and instances start in this pool too.
Thank you very much for your help.
