### ISSUE TITLE
AgentPool feature at profile configuration basic implementation (Required for SakuraUI pool visibility with TeamCity v2021.1 when 0 VMs)

### ISSUE THREAD

**Issue by axel3rd** [yandex-qatools/teamcity-openstack-plugin#64]
(following [comment](https://github.com/yandex-qatools/teamcity-openstack-plugin/issues/62#issuecomment-857663471)):  On TeamCity 2021.1, when no agents are up, the OpenStack pool seems not visible in Sakura UI (http://teamcity.host.com/agents/overview):

![fixed](https://user-images.githubusercontent.com/2912441/122088182-ce865300-ce05-11eb-9ecb-9c23f27c3a18.png)

To analyse, any feedback is welcome.

**Comment by axel3rd** [comment]
PI: It was working fine on TeamCity v2020.2.2.

**Comment by axel3rd** [comment]
https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/4012881d0f46c23f8550ffe4f3dde5f6c3723a7d/pom.xml#L9

Tested with a local build using:
```
<teamcity.version>2021.1</teamcity.version>
```

Doesn't fix the problem. When 0 agent started, profile is not displayed in pool (see previous screenshot) ; but when agent(s) is started, it is displayed:

![image](https://user-images.githubusercontent.com/2912441/122091000-a5b38d00-ce08-11eb-8bea-4ac81e52e819.png)

**Comment by axel3rd** [comment]
@paksv : Sorry to bother you with that, but:
1. AWS cloud profile is working fine on v2021.1 => cloud plugins (like this one) requires some updates for v2021.1 support ?
2. or it smells a bug on TeamCity side with last change(s) on SakuraUI (2020.2 -> 2021.1) ?

I'm not sure of the direction to dig 😢 ...

**Comment by paksv** [comment]
The UI should display here every `CloudImage` that is returned by `CloudClientEx.getImages()` and for which `CloudClientEx.canStartNewInstanceWithDetails` returns `CanStartNewInstanceResult.yes()` or # of started instances is > 0 (your case). So, please check first whether `CloudClientEx.canStartNewInstanceWithDetails` actually returns `CanStartNewInstanceResult.yes()` for CloudImages w/out instances

**Comment by axel3rd** [comment]
Many thanks @paksv, I will check behavior between v2020.2.2 & 2021.1 here

https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/4012881d0f46c23f8550ffe4f3dde5f6c3723a7d/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudClient.java#L181-L207

**Comment by axel3rd** [comment]
> So, please check first whether CloudClientEx.canStartNewInstanceWithDetails actually returns CanStartNewInstanceResult.yes()

@paksv : I have checked this point by adding some debug logs. The return is **always** `CanStartNewInstanceResult.yes()`, even when cloud profile is updated:

```
jetbrains.buildServer.clouds. - Create image  [CLOUD_1_HPE_Ubuntu_18.04] ...
jetbrains.buildServer.clouds. - Restore potential instances for openstack image: CLOUD_1_HPE_Ubuntu_18.04
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 5
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 5
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 5
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 5
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 5
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
[2021-06-21 10:06:52,731]   INFO [nio-8111-exec-3] - .web.admin.UpdateProfileAction - Updating cloud profile: id=NOVA-5
[2021-06-21 10:06:52,734]   INFO [nio-8111-exec-3] - r.impl.ProjectCloudManagerImpl - Updating profile NOVA-5
[2021-06-21 10:06:52,735]   INFO [nio-8111-exec-3] - .server.impl.CloudEventsLogger - Profile reloaded: NOVA-5 and is enabled
jetbrains.buildServer.clouds. - Create image  [CLOUD_1_HPE_Ubuntu_18.04] ...
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 6
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 6
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 6
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 6
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
jetbrains.buildServer.clouds. - Restore potential instances for openstack image: CLOUD_1_HPE_Ubuntu_18.04
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstance / i: 0 / instanceCap: 6
jetbrains.buildServer.clouds. - ALIX DEBUG - canStartNewInstanceWithDetails / return YES
```

IMO it could be a regression in SakuraUI (works fine on v2020.2.2, not on v2021.1).

**Comment by axel3rd** [comment]
Link with TeamCity issue: [TW-71939](https://youtrack.jetbrains.com/issue/TW-71939).

**Comment by axel3rd** [comment]
Synthesis of [TW-71939](https://youtrack.jetbrains.com/issue/TW-71939)
- TeamCity 2021.1 is using an API to retrieve images
- When AgentPool feature is not implemented (like this plugin), the key **agentPoolId** is empty and not displayed

https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/4012881d0f46c23f8550ffe4f3dde5f6c3723a7d/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java#L244-L248

According JavaDoc:
```java
      /**
       * Internal agent pool id associated with this cloud image. <br/>
       * If this feature is not implemented, the function must return null. <br/>
       * <strong>Must use {@link CloudImageParameters#getAgentPoolId()} if returns non-null value. </strong>
       * @return internal pool id
       * @since 10.0
       */
      @Nullable
      Integer getAgentPoolId();
```

---

Not sure to fully understand the concept of *Agent Pool feature*, because I have tested to create a TeamCity Agent pool with an OpenStack image and it works 😢.

**Comment by paksv** [comment]
Thanks, just noticed the same behaviour with LocalCloud plugin (that we use for testing). The image doesn't appear in the new UI, but still visible in the old UI (so that can be used as a workaround)

**Comment by axel3rd** [comment]
@paksv : Agree with you that this problem is minor/cosmetic and a sustainable workaround is existing.

In // of [TW-71939](https://youtrack.jetbrains.com/issue/TW-71939) potential fix (ie: *agentPoolId* not in API response = consider pool 0 for this image), I'm wondering about if a (simple) solution is existing on plugin to fix it.

The *feature "getAgentPoolId"* is a "direct" definition of pool in cloud profile page, like [teamcity-local-cloud](https://github.com/JetBrains/teamcity-local-cloud/blob/v2.0/src/jetbrains/buildServer/clouds/local/LocalCloudClient.java#L73) (but you said it doesn't work) or [teamcity-amazon-ecs-plugin](https://github.com/JetBrains/teamcity-amazon-ecs-plugin/blob/master/aws-ecs-server/src/main/kotlin/jetbrains/buildServer/clouds/ecs/EcsCloudImageData.kt#L33):
![image](https://user-images.githubusercontent.com/2912441/123080555-58917580-d41d-11eb-9d0d-f11185731761.png)

But using previous agent pool page (http://teamcity.company.com/agents.html?tab=agentPools) is working fine to create pool and affect cloud image(s) (even if `getAgentPoolId returns null`). 
So feature "affect an image/VMs to a specific pool" is OK, even if cannot defined during cloud profile configuration (like AWS plugin).

`getAgentPoolId returns 0` could be a (poor, yes) fix for plugin ? Or it will break any pool association, considering that it enforces *default* pool forever ?

**Comment by axel3rd** [comment]
> getAgentPoolId returns 0 could be a (poor, yes) fix for plugin ? Or it will break any pool association, considering that it enforces default pool forever ?

After some quick test, it seems fix the problem:
```java
    @Nullable
    @Override
    public Integer getAgentPoolId() {
        // Image are affected to 'default' agents pool at creation (required for TeamCity v2021.1 / TW-71939)
        // Global "Agents Pools" TeamCity feature should be used to affect image(s) to some pool if needed
        return 0;
    }
```

The image is correctly displayed in new SakuraUI pool visibility with TeamCity v2021.1, and if image affected to some specific pool, image and VMs (created from it) is visible into this specific pool.

@paksv : If you see any negative impacts, it is welcome 😁 ; otherwise I will probably implement it in next version 😊.

**Comment by paksv** [comment]
@axel3rd , the potential issue with that fix would be inability to put the AgentType (i.e. CloudImage) into any pool other than Default (that has id=0). I think this could work as a temporary workaround, but in a long run it would be better to at least add this parameter to `clouds.openstack.images`, so a user can manage this value.

Of course, we'll need to fix the issue on our side as well.

**Comment by axel3rd** [comment]
@paksv : Thanks for the feedback.

**Comment by axel3rd** [comment]
Snapshot version: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildSnapshotIntegration/3540665:id/cloud-openstack.zip) (**v1.6**).

**Comment by axel3rd** [comment]
Release **v1.6** done: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_Release/3561870:id/cloud-openstack.zip)

**Comment by leo-rezaei** [comment]
@axel3rd With this change, I have always my agents under the default pool! any solution to put my cloud profile into the right pool?

**Comment by axel3rd** [comment]
@mhmd-rezaei : At Openstack profile creation yes, but you can configure a pool with this image in http(s)://teamcity.company.com/agents.html?tab=agentPools:

![image](https://user-images.githubusercontent.com/2912441/152404144-f1a79aa0-a6cf-4ccf-a6ce-3d7590dea3c4.png)

**Comment by leo-rezaei** [comment]
@axel3rd I tried to move my cloud profile to the right pool, but when I search for the cloud profile name there, it won't show up in the list to select! 
FYI:  I have version 2021.2.2, and I used exactly the page you mentioned. Just went under the right pool name and clicked on assign agents button. then I couldn't find the cloud profile name from there!

**Comment by axel3rd** [comment]
@mhmd-rezaei : My previous screenshot was done with v2021.2.2 ... so i don't really know what to say.

Is the pool "correct" (without any error) in http(s)://teamcity.company.com/agents.html?tab=clouds, did you have start some VMs with success ?
